name: gap
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.7.16=h7a1cb2a_0
  - readline=8.3=hc2a1206_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.38.4=py37h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.1.0
      - aiocontextvars==0.2.2
      - aiofiles==22.1.0
      - aiosqlite==0.19.0
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asn1crypto==1.5.1
      - attrs==24.2.0
      - babel==2.14.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.3
      - bleach==6.0.0
      - boto==2.49.0
      - botocore==1.33.13
      - cached-property==1.5.2
      - cachetools==5.5.2
      - cffi==1.15.1
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - comm==0.1.4
      - conda-pack==0.8.0
      - contextvars==2.4
      - cryptography==45.0.7
      - cycler==0.11.0
      - cython==3.0.12
      - dask==2022.2.0
      - dataclasses==0.6
      - debugpy==1.7.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docutils==0.20.1
      - dpcpp-cpp-rt==2025.3.1
      - easydict==1.13
      - einops==0.6.1
      - entrypoints==0.4
      - exceptiongroup==1.3.1
      - fastjsonschema==2.21.2
      - fonttools==4.38.0
      - fqdn==1.5.1
      - fsspec==2023.1.0
      - ftfy==6.1.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - glog==0.3.1
      - google-auth==2.41.1
      - google-auth-oauthlib==0.4.6
      - grpcio==1.62.3
      - h5py==3.8.0
      - idna==3.10
      - imageio==2.31.2
      - immutables==0.19
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - intel-cmplr-lib-rt==2025.3.1
      - intel-cmplr-lib-ur==2025.3.1
      - intel-cmplr-lic-rt==2025.3.1
      - intel-opencl-rt==2025.3.1
      - intel-openmp==2025.3.1
      - intel-sycl-rt==2025.3.1
      - iopath==0.1.10
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.16
      - jsonpointer==3.0.0
      - jsonschema==4.17.3
      - jupyter==1.1.1
      - jupyter-client==7.4.9
      - jupyter-console==6.6.3
      - jupyter-core==4.12.0
      - jupyter-events==0.6.3
      - jupyter-server==1.24.0
      - jupyter-server-fileid==0.9.3
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.8
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.5
      - locket==1.0.0
      - loguru==0.7.3
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mkl==2025.3.0
      - mkl-fft==1.3.1
      - mkl-random==1.2.2
      - mkl-service==2.4.0
      - msgpack==1.0.5
      - msgpack-numpy==0.4.8
      - multimethod==1.9.1
      - nbclassic==1.2.0
      - nbclient==0.7.4
      - nbconvert==7.6.0
      - nbformat==5.8.0
      - nest-asyncio==1.6.0
      - networkx==2.6.3
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numpy==1.21.6
      - oauthlib==3.2.2
      - onemkl-license==2025.3.0
      - opencv-python==4.12.0.88
      - packaging==24.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - partd==1.4.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - portalocker==2.7.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.48
      - protobuf==3.20.3
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pygments==2.17.2
      - pyopenssl==25.3.0
      - pyparsing==3.1.4
      - pyrsistent==0.19.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-gflags==3.1.2
      - python-json-logger==3.0.1
      - pytz==2025.2
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - pyzmq==26.2.1
      - qtconsole==5.4.4
      - qtpy==2.4.3
      - regex==2024.4.16
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rsa==4.9.1
      - ruamel-yaml==0.18.13
      - ruamel-yaml-clib==0.2.8
      - s3transfer==0.8.2
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.4.1
      - tabulate==0.9.0
      - tbb==2022.3.0
      - tcmlib==1.4.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - tensorpack==0.11
      - termcolor==2.3.0
      - terminado==0.17.1
      - testpath==0.6.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - tinycss2==1.2.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.1
      - torch==1.8.1+cu111
      - torchaudio==0.8.1
      - torchpack==0.2.2
      - torchvision==0.9.1+cu111
      - tornado==6.2
      - tqdm==4.67.1
      - traitlets==5.9.0
      - typing-extensions==4.7.1
      - umf==1.0.2
      - uri-template==1.3.0
      - urllib3==1.26.20
      - wcwidth==0.2.14
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.15
      - y-py==0.6.2
      - yacs==0.1.8
      - ypy-websocket==0.8.4
      - zipp==3.15.0
prefix: /home/amine/anaconda3/envs/gap
